-- C:\tmp\dosi15\csci_sta.avt
--
-- Generated for Oracle 10g on Tue Oct 23  17:41:19 2012 by Server Generator 10.1.2.11.12


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ETAT_EVALUATION_ENTREPRISE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_EVALUATION_ENTREPRISE', 'VAL', NULL, 'VAL', 'Validée')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_EVALUATION_ENTREPRISE', 'EC', NULL, 'EC', 'En cours de notation')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ETAT_OFFRE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_OFFRE', 'OUV', NULL, 'OUV', 'Ouverte')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_OFFRE', 'POU', NULL, 'POUR', 'Pourvue')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_OFFRE', 'ANN', NULL, 'ANN', 'Annulée')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'SALLE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('SALLE', 'LC117A', NULL, 'LC117A', 'Salle de réunion N°1')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('SALLE', 'LC117B', NULL, 'LC117B', 'Salle de réunion N°2')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('SALLE', 'Amphi P', NULL, 'Amphi P', 'Amphi Pédagogique')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'CODE_NOTE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'A+', NULL, 'A+', 'Excellent')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'A', NULL, 'A', 'Très bien')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'A-', NULL, 'A-', 'Très bien -')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'B-', NULL, 'B-', 'Bien -')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'B+', NULL, 'B+', 'Bien +')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'B', NULL, 'B', 'Bien')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'C+', NULL, 'C+', 'Assez Bien +')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'C', NULL, 'C', 'Assez Bien')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'C-', NULL, 'C-', 'Assez Bien -')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'D+', NULL, 'D+', 'Passable +')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'D', NULL, 'D', 'Passable')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'D-', NULL, 'D-', 'Passable -')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'E+', NULL, 'E+', 'Insuffisant+')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'E', NULL, 'E', 'Insuffisant')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'E-', NULL, 'E -', 'Insuffisant -')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('CODE_NOTE', 'F', NULL, 'F', 'Mauvais')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'INTERLOCUTEUR'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('INTERLOCUTEUR', 'ETU', NULL, 'ETU', 'Etudiant')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('INTERLOCUTEUR', 'ENT', NULL, 'ENT', 'Entreprise')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'NIVEAU_REQUIS'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('NIVEAU_REQUIS', 'BAC+1', NULL, 'BAC+1', 'Bac+1')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('NIVEAU_REQUIS', 'BAC+2', NULL, 'BAC+2', 'Bac+2')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('NIVEAU_REQUIS', 'BAC+3', NULL, 'BAC+3', 'Licence')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('NIVEAU_REQUIS', 'BAC+4', NULL, 'BAC+4', 'Master 1ère année')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('NIVEAU_REQUIS', 'BAC+5', NULL, 'BAC+5', 'Master 2ème année')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ETAT_CONVENTION'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_CONVENTION', 'ELA', NULL, 'ELA', 'Elaboration en cours')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_CONVENTION', 'ENT', NULL, 'ENT', 'Signature entreprise en cours')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_CONVENTION', 'UBO', NULL, 'UBO', 'Signature UBO en cours')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_CONVENTION', 'VAL', NULL, 'VAL', 'Validée par l''UBO')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ETAT_STRUCTURE_EVAL'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_STRUCTURE_EVAL', 'ELA', NULL, 'ELA', 'En cours d''élaboration')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_STRUCTURE_EVAL', 'APP', NULL, 'APP', 'Applicable')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_STRUCTURE_EVAL', 'ARC', NULL, 'ARC', 'Archivée')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'TYPE_CONTACT'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_CONTACT', 'VISIT', NULL, 'VST', 'Visite en entreprise')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_CONTACT', 'TEL', NULL, 'TEL', 'Téléphone')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_CONTACT', 'VISIO', NULL, 'VISIO', 'Visioconférence')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_CONTACT', 'MAIL', NULL, 'MAIL', 'Email')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ETAT_STAGE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_STAGE', 'ELA', NULL, 'ELA', 'Elaboration')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_STAGE', 'EC', NULL, 'EC', 'En cours')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_STAGE', 'EVA', NULL, 'EVA', 'Evalué')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ETAT_STAGE', 'ANN', NULL, 'ANN', 'Annulé')
/

COMMIT
/

