-- C:\tmp\dosi15\csci_sta_adm.con
--
-- Generated for Oracle 10.2 on Wed Oct 24  08:52:54 2012 by Server Generator 10.1.2.11.12
  

 

PROMPT Creating Foreign Key on 'PROMOTION'
ALTER TABLE PROMOTION ADD (CONSTRAINT
 PRO_STRE_FK FOREIGN KEY 
  (NO_EVALUATION) REFERENCES STRUCTURE_EVALUATION
  (NO_EVALUATION))
/

PROMPT Creating Foreign Key on 'PROMOTION'
ALTER TABLE PROMOTION ADD (CONSTRAINT
 PRO_NOTS_FK FOREIGN KEY 
  (NO_BAREME) REFERENCES NOTATION_STAGE
  (NO_BAREME))
/


