-- C:\tmp\dosi15\csci_sta.sqs
--
-- Generated for Oracle 10g on Tue Oct 23  17:41:19 2012 by Server Generator 10.1.2.11.12
 
PROMPT Creating Sequence 'NOTS_SEQ'
CREATE SEQUENCE NOTS_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'OFF_SEQ'
CREATE SEQUENCE OFF_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'STRE_SEQ'
CREATE SEQUENCE STRE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'AVE_SEQ'
CREATE SEQUENCE AVE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'CODN_SEQ'
CREATE SEQUENCE CODN_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'SOUT_SEQ'
CREATE SEQUENCE SOUT_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'CRITE_SEQ'
CREATE SEQUENCE CRITE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

