-- C:\tmp\dosi15\csci_adm.ind
--
-- Generated for Oracle 10g on Tue Oct 23  16:28:09 2012 by Server Generator 10.1.2.11.12
  

PROMPT Creating Index 'ETU_PRO_FK_I'
CREATE INDEX ETU_PRO_FK_I ON ETUDIANT
 (ANNEE_PRO)
/

PROMPT Creating Index 'ETU_COM_FK_I'
CREATE INDEX ETU_COM_FK_I ON ETUDIANT
 (CODE_COM)
/

PROMPT Creating Index 'EMP_ENT_FK_I'
CREATE INDEX EMP_ENT_FK_I ON EMPLOYE
 (NO_ENTREPRISE)
/

PROMPT Creating Index 'POE_ENT_FK_I'
CREATE INDEX POE_ENT_FK_I ON POSTE_ENTREPRISE
 (NO_ENTREPRISE)
/

PROMPT Creating Index 'POE_DIP_FK_I'
CREATE INDEX POE_DIP_FK_I ON POSTE_ENTREPRISE
 (NO_ETUDIANT_NAT)
/

PROMPT Creating Index 'CAN_PRO_FK_I'
CREATE INDEX CAN_PRO_FK_I ON CANDIDAT
 (ANNEE_PRO)
/


