-- C:\tmp\dosi15\csci_adm.avt
--
-- Generated for Oracle 10g on Tue Oct 23  16:28:09 2012 by Server Generator 10.1.2.11.12


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'TYPE_EMPLOI'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_EMPLOI', 'CDI', NULL, 'CDI', 'Contrat à durée indéterminée')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_EMPLOI', 'CDD', NULL, 'CDD', 'Contrat à durée déterminée')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_EMPLOI', 'SE', NULL, 'SE', 'Sans emploi')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('TYPE_EMPLOI', 'CNE', NULL, 'CNE', 'Contrat Nouvelle Embauche')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'MOYEN_OBTENTION_EMPLOI'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('MOYEN_OBTENTION_EMPLOI', 'STA', NULL, 'STA', 'Suite au stage')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('MOYEN_OBTENTION_EMPLOI', 'SPO', NULL, 'SPO', 'Candidature Spontanée')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'PROCESSUS_STAGE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('PROCESSUS_STAGE', 'RECH', NULL, 'RECH', 'Recherche en cours')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('PROCESSUS_STAGE', 'EC', NULL, 'EC', 'Stage en cours')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('PROCESSUS_STAGE', 'TUT', NULL, 'TUT', 'Tuteurs attribués')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('PROCESSUS_STAGE', 'SOUT', NULL, 'SOUT', 'Sessions de soutenance définies')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('PROCESSUS_STAGE', 'EVAL', NULL, 'EVAL', 'Stage evalué')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'SERVICE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('SERVICE', 'EP', NULL, 'EP', 'Equipe Projet')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('SERVICE', 'RetD', NULL, 'RetD', 'Recherche et Développement')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('SERVICE', 'QUA', NULL, 'QUA', 'Qualité')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'DOMAINE_ACTIVITE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('DOMAINE_ACTIVITE', 'BANQ', NULL, 'BANQ', 'Domaine bancaire')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('DOMAINE_ACTIVITE', 'SSII', NULL, 'SSII', 'Société de services en ingénierie informatique')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('DOMAINE_ACTIVITE', 'TEL', NULL, 'TEL', 'Domaine de la téléphonie')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'FONCTION'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'GER', NULL, 'GER', 'Gérant')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'DACH', NULL, 'DACH', 'Directeur des Achats')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'IE', NULL, 'IE', 'Ingénieur d''Etudes')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'ING', NULL, 'ING', 'Ingénieur')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'DIR', NULL, 'DIR', 'Directeur')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'DT', NULL, 'DT', 'Directeur Technique')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'RREC', NULL, 'RREC', 'Responsable Recrutement')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'RAG', NULL, 'RAG', 'Responsable d''Agence')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'CDP', NULL, 'CDP', 'Chef de Projet')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'RQ', NULL, 'RQ', 'Responsable Qualité')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'DRH', NULL, 'DRH', 'Directeur des Ressources Humaines')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('FONCTION', 'COMM', NULL, 'COMM', 'Commercial')
/

COMMIT
/

